{% set name = "vector" %}
{% set version = "1.6.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vector-{{ version }}.tar.gz
  sha256: ee739d3bb65140ddc09d3fa954191335b0e0c640d46a693ae0b17a94641e7838

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - numpy >=1.13.3
    - python >={{ python_min }}
    - importlib-metadata >=0.22
    - typing-extensions
    - packaging >=19

test:
  imports:
    - vector
    - vector.backends
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/vector
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Saransh-cpp
    - conda-forge/scikit-hep
