{% set name = "vector" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vector-{{ version }}.tar.gz
  sha256: 41ec731fb67ea35af2075eb3a4d6c83ef93b580dade63010821cbc00f1b98961

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - numpy >=1.13.3
    - python >=3.8
    - importlib_metadata >=0.22
    - typing-extensions
    - packaging >=19

test:
  imports:
    - vector
    - vector.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/vector
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Saransh-cpp
    - conda-forge/scikit-hep
