schema_version: 1

context:
  name: vector
  version: 1.6.1
  python_min: 3.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/vector-${{ version }}.tar.gz
  sha256: 59982d0ce553d35f76c63396b57d7fcf5004deab33270bfdb6e54c65db62d6e4

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.8.*
    - hatchling
    - hatch-vcs
  run:
    - numpy >=1.13.3
    - python >=${{ python_min }}
    - importlib-metadata >=0.22
    - typing-extensions
    - packaging >=19

tests:
  - python:
      imports:
        - vector
        - vector.backends
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/vector

extra:
  recipe-maintainers:
    - Saransh-cpp
    - conda-forge/scikit-hep
