schema_version: 1

context:
  name: vector
  version: "1.8.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/vector-${{ version }}.tar.gz
  sha256: 58f95e9e24463851ca34176a20df2fd2e80b41d78615e5b1f7ae4bf313424ca6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - numpy >=1.19.3
    - python >=${{ python_min }}
    - packaging >=20
tests:
  - python:
      imports:
        - vector
        - vector.backends
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/vector

extra:
  recipe-maintainers:
    - Saransh-cpp
    - conda-forge/scikit-hep
